### ISSUE TITLE
nextjs version 변경 검토 (v15 -> v14)

### ISSUE THREAD

**Issue by Remian103** [chueok/sns-style-group-album#17]
nextjs, react 관련 version 호환 이슈가 지속적으로 나타나고 있어, 버전 다운그레이드 검토가 필요함.

## 현재 발생하는/존재하는 이슈
- storybook 설치 이후 apps/web 이 정상 빌드되지 않음.
  <img width="1158" alt="image" src="https://github.com/user-attachments/assets/134db8ea-e78f-4762-b1a6-456655a1a906">
  - react 버전이 맞지 않다는 오류 발생
  - npm install 시 npm workspace 관련 node_modules 의 hoisting 으로 발생하는 이슈로 보임
    - `/node_modules` 에 설치된 react 버전: v18.x
    - `/apps/web/node_modules` 에 설치된 react 버전: v19.0.0-rc.xx
    - `next` 모듈 위치: `/node_modules`
    - `/node_modules/next/dist/build/webpack-config.js` 에서 `require` 를 통해 react 패키지를 불러오는데, 이 때 `require` 는 process 실행위치가 아닌 는 **file 위치**를 기반으로 패키지를 탐색함.
    - `/node_modules/next/dist/build/webpack-config.js` 에서 가까운 node_modules 를 탐색하기 때문에 `/node_modules/react` 를 불러와 18 버전으로 인식되어 에러 발생..

- @repo/ui 에서 사용하는 react 버전과 Nextjs 내 react 버전 다름
  - shadcn/ui 에서 사용되는 lucie-react 가 react 19 와 호환되지 않아 별도 버전 설치하여 사용중

- @type/react 19 버전이 존재하지 않음.

### 1. 내부에서 사용하는 모든 react 버전을 19.0.0-rc.xx 버전으로 변경
좋아보이지만 현재 lucie-react, storybook 등 react19 를 peer-dependency 로 지원하지 않는 패키지들 존재
이 경우, `npm install` 은 에러가 발생하고, `npm install --legacy-peer-deps` 를 사용해 peer-dependency 를 무시해야 패키지 설치 가능
하지만 설치하더라도 storybook 이 react 19 를 지원하지 않는 것으로 보임.. (화면 안뜸;)

### 2. nextjs 버전 v14 로 다운그레이드
이 경우, 호환성 이슈 해결 가능

**Comment by ch-jwoo** [comment]
Next 14버전으로 변경하는 것에 동의합니다
